name: Build, Push and Deploy Node Image to Google Cloud Platform

on:
  push:
    branches: [Deploy-Server]

jobs:
  build-deploy-gcr:
    name: Build and Deploy to GCP
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: backend-server
      PROJECT_ID: tecnologias-web-404018
      CLOUD_SDK_AUTH_TOKEN: ${{ secrets.CLOUD_SDK_AUTH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.CLOUD_SDK_AUTH_TOKEN }}

      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build Docker Image
        run: |
          cd server
          docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet

      - name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: v1.0.0
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $IMAGE_NAME \
            --image gcr.io/$PROJECT_ID/$IMAGE_NAME:latest \
            --platform managed \
            --region us-central1 \
            --memory 128Mi \
            --cpu 1 \
            --allow-unauthenticated
