name: Deploy Server to Cloud Run

on:
  push:
    branches:
      - Deploy-Server

jobs:
  deploy:
    runs-on: ubuntu:20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true
      - name: Build Docker Image
        run: |-
          cd server
          docker build -t $IMAGE_NAME:latest .
      - name: Build and push Docker image
        run: |-
          cd server
          gcloud auth configure-docker --quiet
          
      - name: Deploy to Cloud Run
        env:
          GIT_TAG: ${{ github.ref }}
        run: |
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG